name: umpire-quiz

services:

  user-service:
    build: .
#    image: bramjanssens/umpire-quiz-user-service:${USER_SERVICE_VERSION}
#    pull_policy: always
    healthcheck:
      test: [ "CMD", "curl", "http://localhost:9080/health/ready" ]
      interval: 2s
      timeout: 10s
      retries: 24
      start_period: 10s
    ports:
      - "9081:9080"
    environment:
      MYSQL_HOSTNAME: "user-service-db"
      MYSQL_PORT: 3306
      MYSQL_DATABASE: "users-db"
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USE_SSL: "true"
    depends_on:
      user-service-db:
        condition: service_healthy
    networks:
      - umpire-network

  user-service-db:
    image: mysql:8.4.0
    volumes:
      - user-service-db-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "users-db"
    ports:
      - "3307:3306"
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      interval: 2s
      timeout: 10s
      start_period: 2s
      retries: 10
    networks:
      - umpire-network

volumes:
  user-service-db-data:

networks:
  umpire-network:
    driver: bridge
